[project]
name = "virtual-room"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
]

[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "ipython>=9.15.0",
    "ruff>=0.16.1",
    "werkzeug>=3.1.8",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort
